# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import automed_pb2 as automed__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in automed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutomedServiceStub(object):
    """AutoMed – counterfeit drug detection via image classification
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/automed.AutomedService/HealthCheck',
                request_serializer=automed__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=automed__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/automed.AutomedService/Predict',
                request_serializer=automed__pb2.PredictRequest.SerializeToString,
                response_deserializer=automed__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.PredictBatch = channel.unary_unary(
                '/automed.AutomedService/PredictBatch',
                request_serializer=automed__pb2.PredictBatchRequest.SerializeToString,
                response_deserializer=automed__pb2.PredictBatchResponse.FromString,
                _registered_method=True)
        self.ListClasses = channel.unary_unary(
                '/automed.AutomedService/ListClasses',
                request_serializer=automed__pb2.ListClassesRequest.SerializeToString,
                response_deserializer=automed__pb2.ListClassesResponse.FromString,
                _registered_method=True)


class AutomedServiceServicer(object):
    """AutoMed – counterfeit drug detection via image classification
    """

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListClasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutomedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=automed__pb2.HealthCheckRequest.FromString,
                    response_serializer=automed__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=automed__pb2.PredictRequest.FromString,
                    response_serializer=automed__pb2.PredictResponse.SerializeToString,
            ),
            'PredictBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBatch,
                    request_deserializer=automed__pb2.PredictBatchRequest.FromString,
                    response_serializer=automed__pb2.PredictBatchResponse.SerializeToString,
            ),
            'ListClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClasses,
                    request_deserializer=automed__pb2.ListClassesRequest.FromString,
                    response_serializer=automed__pb2.ListClassesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automed.AutomedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('automed.AutomedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutomedService(object):
    """AutoMed – counterfeit drug detection via image classification
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automed.AutomedService/HealthCheck',
            automed__pb2.HealthCheckRequest.SerializeToString,
            automed__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automed.AutomedService/Predict',
            automed__pb2.PredictRequest.SerializeToString,
            automed__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automed.AutomedService/PredictBatch',
            automed__pb2.PredictBatchRequest.SerializeToString,
            automed__pb2.PredictBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/automed.AutomedService/ListClasses',
            automed__pb2.ListClassesRequest.SerializeToString,
            automed__pb2.ListClassesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
