# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: automed.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'automed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rautomed.proto\x12\x07\x61utomed\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\x0ePredictRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"P\n\x0fPredictResponse\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x12\x14\n\x0cis_authentic\x18\x03 \x01(\x08\"@\n\x13PredictBatchRequest\x12)\n\x08requests\x18\x01 \x03(\x0b\x32\x17.automed.PredictRequest\"E\n\x14PredictBatchResponse\x12-\n\x0bpredictions\x18\x01 \x03(\x0b\x32\x18.automed.PredictResponse\"\x14\n\x12ListClassesRequest\"@\n\x13ListClassesResponse\x12\x13\n\x0b\x63lass_names\x18\x01 \x03(\t\x12\x14\n\x0cis_authentic\x18\x02 \x03(\x08\x32\xaf\x02\n\x0e\x41utomedService\x12H\n\x0bHealthCheck\x12\x1b.automed.HealthCheckRequest\x1a\x1c.automed.HealthCheckResponse\x12<\n\x07Predict\x12\x17.automed.PredictRequest\x1a\x18.automed.PredictResponse\x12K\n\x0cPredictBatch\x12\x1c.automed.PredictBatchRequest\x1a\x1d.automed.PredictBatchResponse\x12H\n\x0bListClasses\x12\x1b.automed.ListClassesRequest\x1a\x1c.automed.ListClassesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'automed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=26
  _globals['_HEALTHCHECKREQUEST']._serialized_end=46
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=48
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=102
  _globals['_PREDICTREQUEST']._serialized_start=104
  _globals['_PREDICTREQUEST']._serialized_end=164
  _globals['_PREDICTRESPONSE']._serialized_start=166
  _globals['_PREDICTRESPONSE']._serialized_end=246
  _globals['_PREDICTBATCHREQUEST']._serialized_start=248
  _globals['_PREDICTBATCHREQUEST']._serialized_end=312
  _globals['_PREDICTBATCHRESPONSE']._serialized_start=314
  _globals['_PREDICTBATCHRESPONSE']._serialized_end=383
  _globals['_LISTCLASSESREQUEST']._serialized_start=385
  _globals['_LISTCLASSESREQUEST']._serialized_end=405
  _globals['_LISTCLASSESRESPONSE']._serialized_start=407
  _globals['_LISTCLASSESRESPONSE']._serialized_end=471
  _globals['_AUTOMEDSERVICE']._serialized_start=474
  _globals['_AUTOMEDSERVICE']._serialized_end=777
# @@protoc_insertion_point(module_scope)
