"""
AutoMed gRPC server – medication image analysis.
Exposes HealthCheck, Predict, PredictBatch, ListClasses.
Run: python grpc_server.py
Generate stubs first: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. automed.proto
"""

import os
import base64
import logging
from concurrent import futures

import grpc

# Generated by protoc (run generate_stubs.sh or the protoc command above)
import automed_pb2
import automed_pb2_grpc

from model_loader import load_model, predict_one

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load model at startup (real inference). If conversion not done, falls back to mock.
MODEL, CLASS_NAMES = load_model()
if MODEL is None:
    logger.warning("Running with MOCK inference. Convert TF.js model and run server again for real inference.")

# Map class name -> is_authentic for ListClasses (customize when you have authentic/counterfeit).
def _is_authentic_for_class(class_name: str) -> bool:
    lower = class_name.lower()
    if "counterfeit" in lower or "fake" in lower:
        return False
    return True  # default for "Class 1", "authentic", etc.


class AutomedServicer(automed_pb2_grpc.AutomedServiceServicer):
    def HealthCheck(self, request, context):
        return automed_pb2.HealthCheckResponse(
            status="healthy",
            message="AutoMed medication image analysis service is running.",
        )

    def Predict(self, request, context):
        image_b64 = request.image_base64
        if not image_b64:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("image_base64 is required")
            return automed_pb2.PredictResponse()

        try:
            raw = base64.b64decode(image_b64)
        except Exception as e:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details(f"Invalid base64 image: {e}")
            return automed_pb2.PredictResponse()

        if MODEL is not None:
            try:
                class_name, probability, is_authentic = predict_one(MODEL, CLASS_NAMES, raw)
                logger.info("Predict: %s %.2f (real inference)", class_name, probability)
                return automed_pb2.PredictResponse(
                    class_name=class_name,
                    probability=probability,
                    is_authentic=is_authentic,
                )
            except Exception as e:
                logger.exception("Inference failed: %s", e)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(str(e))
                return automed_pb2.PredictResponse()

        logger.info("Predict: received image, %d bytes (mock)", len(raw))
        first_class = CLASS_NAMES[0] if CLASS_NAMES else "Class 1"
        return automed_pb2.PredictResponse(
            class_name=first_class,
            probability=0.85,
            is_authentic=_is_authentic_for_class(first_class),
        )

    def PredictBatch(self, request, context):
        if not request.requests:
            context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
            context.set_details("requests must contain at least one image")
            return automed_pb2.PredictBatchResponse()
        predictions = []
        first_class = CLASS_NAMES[0] if CLASS_NAMES else "Class 1"
        for i, req in enumerate(request.requests):
            image_b64 = req.image_base64
            if not image_b64:
                context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
                context.set_details(f"request[{i}]: image_base64 is required")
                return automed_pb2.PredictBatchResponse()
            try:
                raw = base64.b64decode(image_b64)
            except Exception as e:
                context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
                context.set_details(f"request[{i}]: invalid base64: {e}")
                return automed_pb2.PredictBatchResponse()
            if MODEL is not None:
                try:
                    class_name, probability, is_authentic = predict_one(MODEL, CLASS_NAMES, raw)
                    predictions.append(
                        automed_pb2.PredictResponse(
                            class_name=class_name,
                            probability=probability,
                            is_authentic=is_authentic,
                        )
                    )
                except Exception as e:
                    logger.exception("PredictBatch[%d] failed: %s", i, e)
                    context.set_code(grpc.StatusCode.INTERNAL)
                    context.set_details(str(e))
                    return automed_pb2.PredictBatchResponse()
            else:
                predictions.append(
                    automed_pb2.PredictResponse(
                        class_name=first_class,
                        probability=0.85,
                        is_authentic=_is_authentic_for_class(first_class),
                    )
                )
        logger.info("PredictBatch: %d images (%s)", len(predictions), "real" if MODEL else "mock")
        return automed_pb2.PredictBatchResponse(predictions=predictions)

    def ListClasses(self, request, context):
        is_authentic = [_is_authentic_for_class(c) for c in CLASS_NAMES]
        return automed_pb2.ListClassesResponse(
            class_names=CLASS_NAMES,
            is_authentic=is_authentic,
        )


def serve():
    port = os.environ.get("GRPC_PORT", "50053")
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    automed_pb2_grpc.add_AutomedServiceServicer_to_server(AutomedServicer(), server)
    server.add_insecure_port(f"[::]:{port}")
    server.start()
    logger.info("AutoMed gRPC server listening on port %s", port)
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
