// source: automed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.ListClassesRequest', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.ListClassesResponse', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.PredictRequest', null, global);
goog.exportSymbol('automed_AJ_dev_outreach_test_1_automed.PredictResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.displayName = 'automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.displayName = 'automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.PredictRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.PredictRequest.displayName = 'automed_AJ_dev_outreach_test_1_automed.PredictRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.PredictResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.PredictResponse.displayName = 'automed_AJ_dev_outreach_test_1_automed.PredictResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.repeatedFields_, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.displayName = 'automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.repeatedFields_, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.displayName = 'automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.ListClassesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.displayName = 'automed_AJ_dev_outreach_test_1_automed.ListClassesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.repeatedFields_, null);
};
goog.inherits(automed_AJ_dev_outreach_test_1_automed.ListClassesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.displayName = 'automed_AJ_dev_outreach_test_1_automed.ListClassesResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest;
  return automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, ""),
message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse;
  return automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string status = 1;
 * @return {string}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.HealthCheckResponse.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.PredictRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
imageBase64: jspb.Message.getFieldWithDefault(msg, 1, ""),
imageFormat: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictRequest}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.PredictRequest;
  return automed_AJ_dev_outreach_test_1_automed.PredictRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictRequest}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageBase64(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageFormat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.PredictRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getImageBase64();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getImageFormat();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string image_base64 = 1;
 * @return {string}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.getImageBase64 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictRequest} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.setImageBase64 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string image_format = 2;
 * @return {string}
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.getImageFormat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictRequest} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictRequest.prototype.setImageFormat = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.PredictResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
className: jspb.Message.getFieldWithDefault(msg, 1, ""),
probability: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
isAuthentic: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.PredictResponse;
  return automed_AJ_dev_outreach_test_1_automed.PredictResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setProbability(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsAuthentic(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.PredictResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClassName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProbability();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getIsAuthentic();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string class_name = 1;
 * @return {string}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.getClassName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.setClassName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float probability = 2;
 * @return {number}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.getProbability = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.setProbability = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional bool is_authentic = 3;
 * @return {boolean}
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.getIsAuthentic = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictResponse.prototype.setIsAuthentic = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
requestsList: jspb.Message.toObjectList(msg.getRequestsList(),
    automed_AJ_dev_outreach_test_1_automed.PredictRequest.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest;
  return automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new automed_AJ_dev_outreach_test_1_automed.PredictRequest;
      reader.readMessage(value,automed_AJ_dev_outreach_test_1_automed.PredictRequest.deserializeBinaryFromReader);
      msg.addRequests(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequestsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      automed_AJ_dev_outreach_test_1_automed.PredictRequest.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PredictRequest requests = 1;
 * @return {!Array<!automed_AJ_dev_outreach_test_1_automed.PredictRequest>}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.getRequestsList = function() {
  return /** @type{!Array<!automed_AJ_dev_outreach_test_1_automed.PredictRequest>} */ (
    jspb.Message.getRepeatedWrapperField(this, automed_AJ_dev_outreach_test_1_automed.PredictRequest, 1));
};


/**
 * @param {!Array<!automed_AJ_dev_outreach_test_1_automed.PredictRequest>} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest} returns this
*/
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.setRequestsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictRequest=} opt_value
 * @param {number=} opt_index
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictRequest}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.addRequests = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, automed_AJ_dev_outreach_test_1_automed.PredictRequest, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchRequest.prototype.clearRequestsList = function() {
  return this.setRequestsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
predictionsList: jspb.Message.toObjectList(msg.getPredictionsList(),
    automed_AJ_dev_outreach_test_1_automed.PredictResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse;
  return automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new automed_AJ_dev_outreach_test_1_automed.PredictResponse;
      reader.readMessage(value,automed_AJ_dev_outreach_test_1_automed.PredictResponse.deserializeBinaryFromReader);
      msg.addPredictions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPredictionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      automed_AJ_dev_outreach_test_1_automed.PredictResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PredictResponse predictions = 1;
 * @return {!Array<!automed_AJ_dev_outreach_test_1_automed.PredictResponse>}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.getPredictionsList = function() {
  return /** @type{!Array<!automed_AJ_dev_outreach_test_1_automed.PredictResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, automed_AJ_dev_outreach_test_1_automed.PredictResponse, 1));
};


/**
 * @param {!Array<!automed_AJ_dev_outreach_test_1_automed.PredictResponse>} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse} returns this
*/
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.setPredictionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!automed_AJ_dev_outreach_test_1_automed.PredictResponse=} opt_value
 * @param {number=} opt_index
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictResponse}
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.addPredictions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, automed_AJ_dev_outreach_test_1_automed.PredictResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.PredictBatchResponse.prototype.clearPredictionsList = function() {
  return this.setPredictionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesRequest}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.ListClassesRequest;
  return automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesRequest}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.toObject = function(opt_includeInstance) {
  return automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
classNamesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
isAuthenticList: (f = jspb.Message.getRepeatedBooleanField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new automed_AJ_dev_outreach_test_1_automed.ListClassesResponse;
  return automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addClassNames(value);
      break;
    case 2:
      var values = /** @type {!Array<boolean>} */ (reader.isDelimited() ? reader.readPackedBool() : [reader.readBool()]);
      for (var i = 0; i < values.length; i++) {
        msg.addIsAuthentic(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClassNamesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getIsAuthenticList();
  if (f.length > 0) {
    writer.writePackedBool(
      2,
      f
    );
  }
};


/**
 * repeated string class_names = 1;
 * @return {!Array<string>}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.getClassNamesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.setClassNamesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.addClassNames = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.clearClassNamesList = function() {
  return this.setClassNamesList([]);
};


/**
 * repeated bool is_authentic = 2;
 * @return {!Array<boolean>}
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.getIsAuthenticList = function() {
  return /** @type {!Array<boolean>} */ (jspb.Message.getRepeatedBooleanField(this, 2));
};


/**
 * @param {!Array<boolean>} value
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.setIsAuthenticList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {boolean} value
 * @param {number=} opt_index
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.addIsAuthentic = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!automed_AJ_dev_outreach_test_1_automed.ListClassesResponse} returns this
 */
automed_AJ_dev_outreach_test_1_automed.ListClassesResponse.prototype.clearIsAuthenticList = function() {
  return this.setIsAuthenticList([]);
};


goog.object.extend(exports, automed_AJ_dev_outreach_test_1_automed);
